### ISSUE TITLE
On iOS 8.1 [library assetForUrl] Photo Streams always returns nil.

### ISSUE THREAD

**Issue by dennisxiaoding** [DennisXiaoDing/DNImagePicker#1]
On iOS 8.1 [library assetForUrl] Photo Streams always returns nil.

```
     [lib enumerateGroupsWithTypes:ALAssetsGroupPhotoStream
                                        usingBlock:^(ALAssetsGroup *group, BOOL *stop)
                 {
                     [group enumerateAssetsWithOptions:NSEnumerationReverse
                                    usingBlock:^(ALAsset *result, NSUInteger index, BOOL *stop) {

                 if([[result valueForProperty:ALAssetPropertyAssetURL] isEqual:dnasset.url])
                 {
                     [weakSelf setCell:blockCell asset:result];
                     *stop = YES;
                 }
             }];
         }
                         failureBlock:^(NSError *error)
         {
             [weakSelf setCell:blockCell asset:nil];
         }];
```

Using enumerateGroupsWithTypes with specific type- ALAssetsGroupPhotoStream

**Comment by atbj505** [comment]
how can I fix this bug in ios8.3? using Singleton?

**Comment by DennisXiaoDing** [comment]
@atbj505 I don understand your question very well. The code attached also works in iOS 8.3.
This issue came from the situation that I wanna to get an asset via the url from the group PhotoStream, but a nil. 
Because of the lifetime of the assetLibrary，when the delegate call back in the scenario the demo gave,
the assetLibrary has been released, so the asset was invalid. This is the reason I delivery the asset's url back to the caller.
I hope I can help you to resolve the problem you met, please do not hesitated to contact me!
